#!/bin/bash
min=1
max=$1
if [[ $1 -gt 0 ]]
then
  output=$((1 + $RANDOM % $max))
  echo $output
else
  echo "[rint][error][exit code: 1] failed to enter positive integer in first parameter."
  exit 1
fi
