#!/bin/bash
min=1
max=$1
command=rint

if [ $# -ne 1 ]
then
  echo "rint installer requires 1 parameter"
  echo "possible paramters: install, uninstall"
  echo "rint setup exiting with error code 1"
  exit 1
fi

if [ "$1" == "uninstall" ]
then
  sudo rm /usr/local/bin/rint
  exit
fi

if ! command -v $command
then
  nocommand=true
fi

if [ ! -f /usr/local/bin/rint ]
then
  nobinary=true
fi

if [ "$nocommand" == "true" ] && \
  [ "$nobinary" == "true" ] && \
  [ "$1" == "install" ]
then
    sudo  ln ./rint /usr/local/bin/rint
fi
